name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build_and_release:
    name: sharun
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install deps
        run: |
          sudo bash -c 'apt update && apt install upx binutils qemu-user-static -y'
          rustup component add rust-src --toolchain nightly
          cargo install cross

      - name: Build x86_64
        run: |
          cargo clean
          cargo build --release
          mv target/x86_64-unknown-linux-musl/release/sharun sharun-x86_64
          cargo build --release --no-default-features
          mv target/x86_64-unknown-linux-musl/release/sharun sharun-x86_64-lite

      - name: Build aarch64
        run: |
          cargo clean
          cross build --release --target aarch64-unknown-linux-musl
          mv target/aarch64-unknown-linux-musl/release/sharun sharun-aarch64
          cross build --release --target aarch64-unknown-linux-musl --no-default-features
          mv target/aarch64-unknown-linux-musl/release/sharun sharun-aarch64-lite

      # https://github.com/aunali1/super-strip
      - name: Strip
        run: |
          "${{ github.workspace }}/.github/sstrip" sharun-*

      - name: UPX
        run: |
          ls sharun-*|xargs -I {} upx -9 --best {} -o {}-upx

      - name: AIO sharun x86_64
        run: |
          docker run --rm -v "${{ github.workspace }}:/root" -w /root --platform=linux/amd64 alpine:latest /root/.github/create_aio_sharun.sh

      - name: AIO sharun aarch64
        run: |
          docker run --rm -v "${{ github.workspace }}:/root" -w /root --platform=linux/arm64 alpine:latest /root/.github/create_aio_sharun.sh

      - name: Release
        uses: actions/upload-artifact@v4
        with:
          path: sharun*
